name: Test Snyk Auth

on:
  push:
    branches:
      - main

jobs:
  snyk-auth-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate Snyk
        run: snyk auth $SNYK_TOKEN
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Test Snyk CLI
        run: snyk test
