  GNU nano 8.2              .github/workflows/tests.yml
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0

    - name: Restore dependencies
      run: dotnet restore CalculatorSolution/CalculatorSolution.sln
    - name: Build solution
      run: dotnet build CalculatorSolution/CalculatorSolution.sln
    - name: Run tests CalculatorSolution/CalculatorSolution.sln

^G Help      ^O Write Out ^F Where Is  ^K Cut       ^T Execute   ^C Location
^X Exit      ^R Read File ^\ Replace   ^U Paste     ^J Justify   ^/ Go To Line

