name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0

    - name: Restore dependencies
      run: dotnet restore C:\Users\star store\Desktop\Pro Calculator\CalculatorSolution\CalculatorTestss
    - name: Build solution
      run: dotnet build C:\Users\star store\Desktop\Pro Calculator\CalculatorSolution\CalculatorTestss

    - name: Run tests
      run: dotnet test C:\Users\star store\Desktop\Pro Calculator\CalculatorSolution\CalculatorTestss
