name : CI/CD pipline

on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest  

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3

  
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0'  

    # Restaure les dépendances
    - name: Restore dependencies
      run: dotnet restore CalculatorSolution/CalculatorTestss

    # Compile le projet
    - name: Build the project
      run: dotnet build CalculatorSolution/CalculatorTestss
    # Exécute les tests
    - name: Run tests
      run: dotnet test CalculatorSolution/CalculatorTestss



